### PR TITLE
pin pip requirements

### PR DESCRIPTION
**Pull request by funkyHat**
using pip-compile-multi (which prevents conflicts between the main &
test requirements, but forces the rename of the requirements files)

### CODE REVIEW

**Comment by funkyHat** [comment]
first passing build in 3 months 🥂 ;) .... though I've just realised this might break pyup? not sure

**Comment by funkyHat** [comment]
but I can't see a configuration file for pyup, so maybe it can just figure it out for itself?

**Comment by kragniz** [comment]
I've not used pip-compile-multi, but it seems like a good idea. Let's see what happens with pyup

**Comment by kragniz** [comment]
@funkyHat as a follow-up, could you add a small item to the docs on how to update these new files?

**Pull request merged**
