### PR TITLE
WIP: Add watching

### PR DESCRIPTION
**Pull request by kragniz**

### CODE REVIEW

**Comment by WangFenjin** [comment]
hi @kragniz ,
do we have plans to finish the watch api? Can't wait to use it... Thanks

**Comment by kragniz** [comment]
Hey, no eta since it's not working right now. Any help would be appreciated!

**Comment by WangFenjin** [comment]
hi @kragniz ,

I will create a new PR based on master about watch.

**Comment by kragniz** [comment]
Great! Looking forward to it

**Comment by kragniz** [comment]
Replaced by #46.

**Pull request closed without merging**
